name: LocationBasedActions
main: net.owlbox.sirmud.LocationBasedActions.LocationBasedActions
version: 0.0.2
author: Ebben Feagan <ebben.feagan@gmail.com>
database: false
depend: [PermissionsEx]

permissions:
   LocationBasedActions.*:
      default: op
      children:
         LocationBasedActions.AutoRank.set: true
         LocationBasedActions.AutoRank.remove: true
         LocationBasedActions.AutoRank.list: true
   LocationBasedActions.AutoRank.set:
      default: op
   LocationBasedActions.AutoRank.remove:
      default: op
   LocationBasedActions.AutoRank.list:
      default: op
      
commands:
   setrankloc:
      description: Allows you to define an area that changes the rank of a Player.
      usage: /setrankloc RankFrom RankTo LocationName
      permission: LocationBasedActions.AutoRank.set
      permission-message: You are not able to set AutoRank locations.
   remrankloc:
      description: Removes a previously defined location.
      usage: /remrankloc LocationName
      permission: LocationBasedActions.AutoRank.remove
      permission-message: You are not able to remove AutoRank locations.
   listrankloc:
      description: Lists previously defined locations.
      usage: /listrankloc
      permission: LocationBasedActions.AutoRank.list
      permission-message: You are not able to list AutoRank locations.